// Первичное наполнение базы.
//
// Отрабатывает только на пустой базе: категории заводятся, если их нет,
// изделия — если в каталоге пусто. Повторные запуски ничего не трогают,
// поэтому правки администратора никогда не затираются.
package main

// seedCategory — раздел каталога из поставки.
type seedCategory struct {
	Name   string
	NameKK string
	NameEN string
	Slug   string
	Order  int
}

// Слаги совпадают с адресами в меню сайта (catalog.html?cat=wood),
// поэтому ссылки в навигации и в каталоге совпадают.
var seedCategories = []seedCategory{
	{"Акция", "Жеңілдік", "Sale", "sale", 10},
	{"Под дерево", "Ағаш өрнегі", "Wood look", "wood", 20},
	{"Ткань", "Мата", "Fabric", "fabric", 30},
	{"Под камень", "Тас өрнегі", "Stone look", "stone", 40},
	{"Матовые", "Күңгірт", "Matte", "matte", 50},
	{"Кожа", "Былғары", "Leather", "leather", 60},
	{"Штукатурка", "Сылақ", "Plaster", "plaster", 70},
	{"Металл", "Металл", "Metal", "metal", 80},
	{"Декоративные рейки", "Сәндік рейкалар", "Decorative slats", "slats", 90},
	{"Бюджетная серия", "Бюджеттік сериясы", "Budget series", "budget", 100},
}

// seedProduct — позиция каталога из прайса. Цены указаны в тенге за одну
// панель по прайсу 2026 года; администратор правит их в панели управления.
type seedProduct struct {
	Title         string
	TitleKK       string
	TitleEN       string
	Description   string
	DescriptionKK string
	DescriptionEN string
	Price         int64
	Image         string
	CategorySlug  string
	Size          string
	Badge         string
}

var seedProducts = []seedProduct{
	{
		Title:         "Панель Lfi 1012",
		TitleKK:       "Lfi 1012 панелі",
		TitleEN:       "Lfi 1012 panel",
		Description:   "Стеновая панель Lfi 1012 по акционной цене. Размер 2800×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Lfi 1012 қабырға панелі жеңілдік бағасымен. Өлшемі 2800×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "Lfi 1012 wall panel at a promotional price. Size 2800×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/lfi-1012.jpg",
		CategorySlug:  "sale",
		Size:          "2800x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель Lfi 1013",
		TitleKK:       "Lfi 1013 панелі",
		TitleEN:       "Lfi 1013 panel",
		Description:   "Стеновая панель Lfi 1013 по акционной цене. Размер 2800×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Lfi 1013 қабырға панелі жеңілдік бағасымен. Өлшемі 2800×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "Lfi 1013 wall panel at a promotional price. Size 2800×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/lfi-1013.jpg",
		CategorySlug:  "sale",
		Size:          "2800x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель 4022",
		TitleKK:       "4022 панелі",
		TitleEN:       "4022 panel",
		Description:   "Стеновая панель 4022 по акционной цене. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "4022 қабырға панелі жеңілдік бағасымен. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "4022 wall panel at a promotional price. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/4022.jpg",
		CategorySlug:  "sale",
		Size:          "3000x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель W 03",
		TitleKK:       "W 03 панелі",
		TitleEN:       "W 03 panel",
		Description:   "Стеновая панель W 03 по акционной цене. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "W 03 қабырға панелі жеңілдік бағасымен. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "W 03 wall panel at a promotional price. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/w-03.jpg",
		CategorySlug:  "sale",
		Size:          "3000x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель 9165-7",
		TitleKK:       "9165-7 панелі",
		TitleEN:       "9165-7 panel",
		Description:   "Стеновая панель 9165-7 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 9165-7 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "9165-7 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/9165-7.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 0915-8",
		TitleKK:       "0915-8 панелі",
		TitleEN:       "0915-8 panel",
		Description:   "Стеновая панель 0915-8 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 0915-8 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "0915-8 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/0915-8.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 9165-8",
		TitleKK:       "9165-8 панелі",
		TitleEN:       "9165-8 panel",
		Description:   "Стеновая панель 9165-8 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 9165-8 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "9165-8 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/9165-8.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 0915-9",
		TitleKK:       "0915-9 панелі",
		TitleEN:       "0915-9 panel",
		Description:   "Стеновая панель 0915-9 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 0915-9 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "0915-9 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/0915-9.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 6013",
		TitleKK:       "6013 панелі",
		TitleEN:       "6013 panel",
		Description:   "Стеновая панель 6013 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 6013 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "6013 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         27000,
		Image:         "/assets/img/panels/6013.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель NB NB 003-1",
		TitleKK:       "NB NB 003-1 панелі",
		TitleEN:       "NB NB 003-1 panel",
		Description:   "Стеновая панель NB NB 003-1 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар NB NB 003-1 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "NB NB 003-1 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         43750,
		Image:         "/assets/img/panels/nb-nb-003-1.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 2006",
		TitleKK:       "2006 панелі",
		TitleEN:       "2006 panel",
		Description:   "Стеновая панель 2006 по акционной цене. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "2006 қабырға панелі жеңілдік бағасымен. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "2006 wall panel at a promotional price. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/2006.jpg",
		CategorySlug:  "sale",
		Size:          "3000x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель 5002",
		TitleKK:       "5002 панелі",
		TitleEN:       "5002 panel",
		Description:   "Стеновая панель 5002 по акционной цене. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "5002 қабырға панелі жеңілдік бағасымен. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "5002 wall panel at a promotional price. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/5002.jpg",
		CategorySlug:  "sale",
		Size:          "3000x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель 5004",
		TitleKK:       "5004 панелі",
		TitleEN:       "5004 panel",
		Description:   "Стеновая панель 5004 по акционной цене. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "5004 қабырға панелі жеңілдік бағасымен. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "5004 wall panel at a promotional price. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/5004.jpg",
		CategorySlug:  "sale",
		Size:          "3000x1220",
		Badge:         "Акция",
	},
	{
		Title:         "Панель 3208-4",
		TitleKK:       "3208-4 панелі",
		TitleEN:       "3208-4 panel",
		Description:   "Стеновая панель 3208-4 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 3208-4 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "3208-4 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         37000,
		Image:         "/assets/img/panels/3208-4.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 324-2",
		TitleKK:       "324-2 панелі",
		TitleEN:       "324-2 panel",
		Description:   "Стеновая панель 324-2 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 324-2 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "324-2 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/324-2.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 324-5",
		TitleKK:       "324-5 панелі",
		TitleEN:       "324-5 panel",
		Description:   "Стеновая панель 324-5 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 324-5 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "324-5 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/324-5.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 324-4",
		TitleKK:       "324-4 панелі",
		TitleEN:       "324-4 panel",
		Description:   "Стеновая панель 324-4 с текстурой дерева. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Ағаш өрнегі бар 324-4 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "324-4 wall panel with a wood texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/324-4.jpg",
		CategorySlug:  "wood",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель W5-02",
		TitleKK:       "W5-02 панелі",
		TitleEN:       "W5-02 panel",
		Description:   "Стеновая панель W5-02 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар W5-02 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "W5-02 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         36000,
		Image:         "/assets/img/panels/w5-02.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель W21-2",
		TitleKK:       "W21-2 панелі",
		TitleEN:       "W21-2 panel",
		Description:   "Стеновая панель W21-2 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар W21-2 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "W21-2 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         36000,
		Image:         "/assets/img/panels/w21-2.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель W20-1",
		TitleKK:       "W20-1 панелі",
		TitleEN:       "W20-1 panel",
		Description:   "Стеновая панель W20-1 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар W20-1 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "W20-1 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         36000,
		Image:         "/assets/img/panels/w20-1.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель W12-1",
		TitleKK:       "W12-1 панелі",
		TitleEN:       "W12-1 panel",
		Description:   "Стеновая панель W12-1 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар W12-1 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "W12-1 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         36000,
		Image:         "/assets/img/panels/w12-1.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель QB 2027",
		TitleKK:       "QB 2027 панелі",
		TitleEN:       "QB 2027 panel",
		Description:   "Стеновая панель QB 2027 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар QB 2027 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "QB 2027 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/qv-2027.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель QB 2008",
		TitleKK:       "QB 2008 панелі",
		TitleEN:       "QB 2008 panel",
		Description:   "Стеновая панель QB 2008 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар QB 2008 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "QB 2008 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/qb-2008.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель QB 2017",
		TitleKK:       "QB 2017 панелі",
		TitleEN:       "QB 2017 panel",
		Description:   "Стеновая панель QB 2017 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар QB 2017 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "QB 2017 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/qb-2017.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель QB 2010",
		TitleKK:       "QB 2010 панелі",
		TitleEN:       "QB 2010 panel",
		Description:   "Стеновая панель QB 2010 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар QB 2010 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "QB 2010 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         32000,
		Image:         "/assets/img/panels/qb-2010.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 8205-4",
		TitleKK:       "8205-4 панелі",
		TitleEN:       "8205-4 panel",
		Description:   "Стеновая панель 8205-4 с текстурой камня. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Тас өрнегі бар 8205-4 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "8205-4 wall panel with a stone texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         30000,
		Image:         "/assets/img/panels/8205-4.jpg",
		CategorySlug:  "stone",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 7204-1",
		TitleKK:       "7204-1 панелі",
		TitleEN:       "7204-1 panel",
		Description:   "Стеновая панель 7204-1 с текстурой камня. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Тас өрнегі бар 7204-1 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "7204-1 wall panel with a stone texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         39000,
		Image:         "/assets/img/panels/7204-1.jpg",
		CategorySlug:  "stone",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 722",
		TitleKK:       "722 панелі",
		TitleEN:       "722 panel",
		Description:   "Стеновая панель 722 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар 722 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "722 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/722.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 723",
		TitleKK:       "723 панелі",
		TitleEN:       "723 panel",
		Description:   "Стеновая панель 723 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар 723 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "723 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/723.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 725",
		TitleKK:       "725 панелі",
		TitleEN:       "725 panel",
		Description:   "Стеновая панель 725 с текстурой ткани. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Мата өрнегі бар 725 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "725 wall panel with a fabric texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/725.jpg",
		CategorySlug:  "fabric",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 6105",
		TitleKK:       "6105 панелі",
		TitleEN:       "6105 panel",
		Description:   "Стеновая панель 6105 с матовой поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Күңгірт беті бар 6105 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "6105 wall panel with a matt surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/6105.jpg",
		CategorySlug:  "matte",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель ХМТ 001",
		TitleKK:       "ХМТ 001 панелі",
		TitleEN:       "ХМТ 001 panel",
		Description:   "Стеновая панель ХМТ 001 с матовой поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Күңгірт беті бар ХМТ 001 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "ХМТ 001 wall panel with a matt surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/hmt-001.jpg",
		CategorySlug:  "matte",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель Т 006",
		TitleKK:       "Т 006 панелі",
		TitleEN:       "Т 006 panel",
		Description:   "Стеновая панель Т 006 с матовой поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Күңгірт беті бар Т 006 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "Т 006 wall panel with a matt surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/t-006.jpg",
		CategorySlug:  "matte",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель Lfi-6032",
		TitleKK:       "Lfi-6032 панелі",
		TitleEN:       "Lfi-6032 panel",
		Description:   "Стеновая панель Lfi-6032 с матовой поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Күңгірт беті бар Lfi-6032 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "Lfi-6032 wall panel with a matt surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/lfi-6032.jpg",
		CategorySlug:  "matte",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель ХМТ 020",
		TitleKK:       "ХМТ 020 панелі",
		TitleEN:       "ХМТ 020 panel",
		Description:   "Стеновая панель ХМТ 020 с матовой поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Күңгірт беті бар ХМТ 020 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "ХМТ 020 wall panel with a matt surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/hmt-020.jpg",
		CategorySlug:  "matte",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель G 007",
		TitleKK:       "G 007 панелі",
		TitleEN:       "G 007 panel",
		Description:   "Стеновая панель G 007 с текстурой кожи. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Былғары өрнегі бар G 007 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "G 007 wall panel with a leather texture. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         30000,
		Image:         "/assets/img/panels/g-007.jpg",
		CategorySlug:  "leather",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 739",
		TitleKK:       "739 панелі",
		TitleEN:       "739 panel",
		Description:   "Стеновая панель 739 под декоративную штукатурку. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Сәндік сылақ өрнегі бар 739 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "739 wall panel with a decorative plaster finish. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/739.jpg",
		CategorySlug:  "plaster",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 741",
		TitleKK:       "741 панелі",
		TitleEN:       "741 panel",
		Description:   "Стеновая панель 741 под декоративную штукатурку. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Сәндік сылақ өрнегі бар 741 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "741 wall panel with a decorative plaster finish. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/741.jpg",
		CategorySlug:  "plaster",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 743",
		TitleKK:       "743 панелі",
		TitleEN:       "743 panel",
		Description:   "Стеновая панель 743 под декоративную штукатурку. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Сәндік сылақ өрнегі бар 743 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "743 wall panel with a decorative plaster finish. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/743.jpg",
		CategorySlug:  "plaster",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 8031",
		TitleKK:       "8031 панелі",
		TitleEN:       "8031 panel",
		Description:   "Стеновая панель 8031 с металлической поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Металл беті бар 8031 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "8031 wall panel with a metallic surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         18000,
		Image:         "/assets/img/panels/8031.jpg",
		CategorySlug:  "metal",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 031",
		TitleKK:       "031 панелі",
		TitleEN:       "031 panel",
		Description:   "Стеновая панель 031 с металлической поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Металл беті бар 031 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "031 wall panel with a metallic surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         31000,
		Image:         "/assets/img/panels/031.jpg",
		CategorySlug:  "metal",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель 009",
		TitleKK:       "009 панелі",
		TitleEN:       "009 panel",
		Description:   "Стеновая панель 009 с металлической поверхностью. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Металл беті бар 009 қабырға панелі. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "009 wall panel with a metallic surface. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         31000,
		Image:         "/assets/img/panels/009.jpg",
		CategorySlug:  "metal",
		Size:          "3000x1220",
	},
	{
		Title:         "Рейка 737",
		TitleKK:       "737 рейкасы",
		TitleEN:       "737 slat",
		Description:   "Декоративная рейка 737. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "737 сәндік рейкасы. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "737 decorative slat. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/737.jpg",
		CategorySlug:  "slats",
		Size:          "3000x1220",
	},
	{
		Title:         "Рейка 738",
		TitleKK:       "738 рейкасы",
		TitleEN:       "738 slat",
		Description:   "Декоративная рейка 738. Размер 3000×1220×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "738 сәндік рейкасы. Өлшемі 3000×1220×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "738 decorative slat. Size 3000×1220×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         25000,
		Image:         "/assets/img/panels/738.jpg",
		CategorySlug:  "slats",
		Size:          "3000x1220",
	},
	{
		Title:         "Панель JL 104",
		TitleKK:       "JL 104 панелі",
		TitleEN:       "JL 104 panel",
		Description:   "Стеновая панель JL 104 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы JL 104 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "JL 104 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         14500,
		Image:         "/assets/img/panels/jl-104.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель G 2607",
		TitleKK:       "G 2607 панелі",
		TitleEN:       "G 2607 panel",
		Description:   "Стеновая панель G 2607 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы G 2607 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "G 2607 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         14500,
		Image:         "/assets/img/panels/g-2607.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель G 2611",
		TitleKK:       "G 2611 панелі",
		TitleEN:       "G 2611 panel",
		Description:   "Стеновая панель G 2611 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы G 2611 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "G 2611 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         14500,
		Image:         "/assets/img/panels/g-2611.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель G 2635",
		TitleKK:       "G 2635 панелі",
		TitleEN:       "G 2635 panel",
		Description:   "Стеновая панель G 2635 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы G 2635 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "G 2635 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         14500,
		Image:         "/assets/img/panels/g-2635.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель G 2625",
		TitleKK:       "G 2625 панелі",
		TitleEN:       "G 2625 panel",
		Description:   "Стеновая панель G 2625 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы G 2625 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "G 2625 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         14500,
		Image:         "/assets/img/panels/g-2625.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель SF 208",
		TitleKK:       "SF 208 панелі",
		TitleEN:       "SF 208 panel",
		Description:   "Стеновая панель SF 208 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы SF 208 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "SF 208 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12500,
		Image:         "/assets/img/panels/sf-208.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель SF 111",
		TitleKK:       "SF 111 панелі",
		TitleEN:       "SF 111 panel",
		Description:   "Стеновая панель SF 111 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы SF 111 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "SF 111 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12500,
		Image:         "/assets/img/panels/sf-111.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель А 88 35-1",
		TitleKK:       "А 88 35-1 панелі",
		TitleEN:       "А 88 35-1 panel",
		Description:   "Стеновая панель А 88 35-1 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы А 88 35-1 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "А 88 35-1 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12000,
		Image:         "/assets/img/panels/a-88-35-1.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель SF 027",
		TitleKK:       "SF 027 панелі",
		TitleEN:       "SF 027 panel",
		Description:   "Стеновая панель SF 027 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы SF 027 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "SF 027 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12000,
		Image:         "/assets/img/panels/sf-027.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель SF 214",
		TitleKK:       "SF 214 панелі",
		TitleEN:       "SF 214 panel",
		Description:   "Стеновая панель SF 214 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы SF 214 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "SF 214 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12500,
		Image:         "/assets/img/panels/sf-214.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель SF 217",
		TitleKK:       "SF 217 панелі",
		TitleEN:       "SF 217 panel",
		Description:   "Стеновая панель SF 217 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы SF 217 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "SF 217 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12500,
		Image:         "/assets/img/panels/sf-217.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель LK 08",
		TitleKK:       "LK 08 панелі",
		TitleEN:       "LK 08 panel",
		Description:   "Стеновая панель LK 08 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы LK 08 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "LK 08 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12000,
		Image:         "/assets/img/panels/lk-08.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель PW 02",
		TitleKK:       "PW 02 панелі",
		TitleEN:       "PW 02 panel",
		Description:   "Стеновая панель PW 02 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы PW 02 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "PW 02 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12000,
		Image:         "/assets/img/panels/pw-02.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель SF 014",
		TitleKK:       "SF 014 панелі",
		TitleEN:       "SF 014 panel",
		Description:   "Стеновая панель SF 014 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы SF 014 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "SF 014 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12500,
		Image:         "/assets/img/panels/sf-014.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
	{
		Title:         "Панель А 822",
		TitleKK:       "А 822 панелі",
		TitleEN:       "А 822 panel",
		Description:   "Стеновая панель А 822 из бюджетной серии. Размер 3000×1200×5 мм, цена указана за одну панель. Продукция сертифицирована в Казахстане.",
		DescriptionKK: "Бюджеттік сериядағы А 822 қабырға панелі. Өлшемі 3000×1200×5 мм, баға бір панельге көрсетілген. Өнім Қазақстанда сертификатталған.",
		DescriptionEN: "А 822 wall panel from the budget series. Size 3000×1200×5 mm, the price is per panel. Certified in Kazakhstan.",
		Price:         12000,
		Image:         "/assets/img/panels/a-822.jpg",
		CategorySlug:  "budget",
		Size:          "3000x1200",
	},
}

// Seed заводит категории и демонстрационные изделия на пустой базе.
func (s *Store) Seed() error {
	cats, err := s.ListCategories()
	if err != nil {
		return err
	}

	if len(cats) == 0 {
		ts := now()
		for _, c := range seedCategories {
			if _, err := s.db.Exec(
				`INSERT INTO categories (name, name_kk, name_en, slug, sort_order, created_at)
                 VALUES (?, ?, ?, ?, ?, ?)`,
				c.Name, c.NameKK, c.NameEN, c.Slug, c.Order, ts); err != nil {
				return err
			}
		}
		logInfo("создано категорий: %d", len(seedCategories))

		if cats, err = s.ListCategories(); err != nil {
			return err
		}
	}

	var products int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM products`).Scan(&products); err != nil {
		return err
	}
	if products > 0 {
		return nil
	}

	bySlug := make(map[string]int64, len(cats))
	for _, c := range cats {
		bySlug[c.Slug] = c.ID
	}

	for _, p := range seedProducts {
		var catID *int64
		if id, ok := bySlug[p.CategorySlug]; ok {
			catID = &id
		}
		if _, err := s.CreateProduct(ProductInput{
			Title:         p.Title,
			TitleKK:       p.TitleKK,
			TitleEN:       p.TitleEN,
			Description:   p.Description,
			DescriptionKK: p.DescriptionKK,
			DescriptionEN: p.DescriptionEN,
			Price:         p.Price,
			ImageURL:      p.Image,
			CategoryID:    catID,
			Status:        StatusActive,
			Size:          p.Size,
			Badge:         p.Badge,
		}); err != nil {
			return err
		}
	}
	logInfo("создано изделий: %d", len(seedProducts))
	return nil
}
